### ISSUE TITLE
Haxball Headless Host

### ISSUE THREAD

**Issue by wohSi** [angerman/hackage.nix#1]
Hey man! 
Can you help doing a bot for haxball?
https://github.com/haxball/haxball-issues/wiki/Headless-Host < - example of var
https://github.com/XHerna/fm-publicbot/blob/f821be34bfc7eae0cb90a5dcd293de8c81489213/3vs3auto < - example of bot
https://github.com/Wazarr94/haxball_bot/blob/master/Level_3/HaxBot_v3.js < - example of bot

**Comment by angerman** [comment]
This seems unrelated to `hackage.nix`.
